name = "topf-deckel"
account_id = "2e7b152ed47c5f821fbf77a7dddd7966"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets" }

[[kv_namespaces]]
binding = "ORDERS_KV"
id = "ab7857df04b6448ba54220a320d394f1"

[[kv_namespaces]]
binding = "STOCK_KV"
id = "a9a45b4740c8422cb1b6f490a12ff8fa"
